Used to address ERROR in src/app/tree/node/node.component.html(7,10): Property 'isMaker' does not exist on type 'TreeDiagramNode | TreeDiagramNodeMaker'.   Property 'isMaker' does not exist on type 'TreeDiagramNode'. src/app/tree/node/node.component.html(14,10): Property 'isMaker' does not exist on type 'TreeDiagramNode | TreeDiagramNodeMaker'.   Property 'isMaker' does not exist on type 'TreeDiagramNode'.